//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day1Paper1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRoster
    {
        public int id { get; set; }
        public string flightId { get; set; }
        public Nullable<int> teamId { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Team Team { get; set; }
    }
}
