//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2023Day1Paper1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wsc2023Day1Paper1DbContext : DbContext
    {
        public Wsc2023Day1Paper1DbContext()
            : base("name=Wsc2023Day1Paper1DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<Crew> Crews { get; set; }
        public virtual DbSet<DateRostered> DateRostereds { get; set; }
        public virtual DbSet<FlightRoster> FlightRosters { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeamAssigned> TeamAssigneds { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
